version: "3.5"

services:
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
    image: elasticsearch:7.10.1
    ports:
      - "9201:9200"
      - "9301:9300"
